<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MX-IT01120" name="My Starbucks test" tests="5" failures="1" timestamp="28 Mar 2018 23:52:23 GMT" time="35.243" errors="0">
  <testcase name="testGiftCard" time="12.02" classname="com.automation.training.StarbucksTest"/>
  <testcase name="testGiftCard" time="9.608" classname="com.automation.training.StarbucksTest">
    <failure type="java.lang.AssertionError" message="expected [Sergio
This is a message for the GIFT CARD. Regards.] but found [Sergio
This is a message for the 2nd GIFT CARD. Regards.]">
      <![CDATA[java.lang.AssertionError: expected [Sergio
This is a message for the GIFT CARD. Regards.] but found [Sergio
This is a message for the 2nd GIFT CARD. Regards.]
	at com.automation.training.StarbucksTest.testGiftCard(StarbucksTest.java:41)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testGiftCard -->
  <testcase name="testMenuCoffe" time="6.045" classname="com.automation.training.StarbucksTest"/>
  <testcase name="testMenuCoffe" time="2.767" classname="com.automation.training.StarbucksTest"/>
  <testcase name="testTextNavsHome" time="0.248" classname="com.automation.training.StarbucksTest"/>
</testsuite> <!-- My Starbucks test -->
